module.exports = {
	serviceName: "general",
	Attribute: "attributes",
	AttributeValue: "attribute-value",
	Banner: "banner",
	Product: "products",
	ProductOption: "product-options",
	Stock: "stocks",
	Category: "categories",
	User: "users",
	Auth: "auth",
	Store: "stores",
	Role: "roles",
	Order: "orders",
	StockHistory: "stock_histories",
	Payment: "payments",
	PriceBook: "price-books",
	Promotion: "promotion",
	Province: "province",
	District: "district",
	Ward: "ward",
	Cart: "cart"
};
