name: deloy

on:
  push:
    branches: [master]
    
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:       
      - name: checkout code
        uses: actions/checkout@v2
       
      - name: run build
        run: docker-compose up -d
        
      - name: login container registry
        run: echo "${{secrets.GIT_HUB_ACCESS_TOKEN}}" | docker login http://ghrc.io -u ${{secrets.USER_NAME}} --password-stdin
        
      - name: Login docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
      - name: push doccker hub
        run: docker-compose push
      
